name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        # We changed verify to package so it explicitly builds the .jar
        run: mvn clean package

      - name: Save the JAR file
        uses: actions/upload-artifact@v4
        with:
          name: my-java-app
          # This tells GitHub where Maven put the compiled file
          path: target/*.jar 